services:
  - type: web
    name: studyly-backend
    runtime: python
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DATABASE_URL
        fromDatabase:
          name: studyly-db
          property: connectionString

databases:
  - name: studyly-db
    plan: free
    region: oregon
    ipAllowList: []  # Required for Render to allow access